import Head from 'next/head';
import { Main } from './Main/Main';
import { CoreProvider } from 'core/CoreProvider';
export default function Home() {
  return (
    <>
      <Head>
        <title>react project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/icon.svg" />
      </Head>
      <CoreProvider>
        <Main />
      </CoreProvider>
    </>
  );
}
